// setting constant value
const DECREASE = 'DECREASE'
const INCREASE = 'INCREASE'
const REMOVE = 'REMOVE'
const CLEAR_CART = 'CLEAR_CART'
const GET_TOTAL = 'GET_TOTAL'
const GET_AMOUNT = 'GET_AMOUNT'

export { DECREASE, INCREASE, REMOVE, CLEAR_CART, GET_TOTAL, GET_AMOUNT }
